(defun binary-search (obj vec)
  (let ((len (length vec)))
    (and (not (zerop len))
         (finder obj vec 0 (- len 1)))))

(defun average (a b)
  (/ (+ a b) 2))

(defun finder (obj vec lo hi)
  (if (equal lo hi)
      (if (eql obj (aref vec lo))
          obj
          nil)
      (let* ((mid (floor (average lo hi)))
             (obj2 (aref vec mid)))
        (if (> obj obj2)
            (finder obj vec (+ 1 mid) hi)
            (if (< obj obj2)
                (finder obj vec lo (- mid 1))
                obj)))))
