(defun fsub (path search replace)
  (with-open-file (f path :direction :input)
    (let ((in-match 0)
          (slen (length search))
          (buffer nil))
      (do ((c (read-char f nil 'eof) (read-char f nil 'eof)))
          ((eql c 'eof))
        (if (eql c (aref search in-match))
            (if (eql (+ in-match 1) slen)
                (progn
                  (format t replace)
                  (setf in-match 0))
                (progn
                  (push buffer c)
                  (incf in-match)))
            (if (null buffer)
                (format t (string c))
                (progn
                  (setf in-match 0)
                  (format t (list-to-str (reverse buffer)))
                  (format t (string c)))))))))

(defun strsub (subject search replace)
  (list-to-str (sub (seq-to-list subject)
                    (seq-to-list search)
                    (seq-to-list replace))))

(defun seq-to-list (seq)
  (do* ((i (length seq) (- i 1))
        (lst nil (push (aref seq i) lst)))
       ((= i 0) lst)))

(defun list-to-str (lst)
  (let ((str (make-string (length lst))))
    (dotimes (i (length str))
      (setf (aref str i) (car lst))
      (setf lst (cdr lst)))
    str))

(defun sub (subject search replace)
  (if (null subject)
      nil
      (multiple-value-bind (rest found) (match subject search)
        (if found
            (append replace (sub rest search replace))
            (cons (car subject) (sub (cdr subject) search replace))))))

(defun match (subject search)
  (cond ((null search)
         (values subject t))
        ((null subject)
         (values nil nil))
        ((eql (car subject) (car search))
         (match (cdr subject) (cdr search)))
        (t (values subject nil))))
