(define (count-change amount)
  (cc amount 5))

(define (cc amount n)
  (cond ((= amount 0) 1)
        ((< amount 0) 0)
        ((= n 0)      0)
        (else (+ (cc amount (- n 1))
                 (cc (- amount (coin-value n)) n)))))

(define (coin-value n)
  (cond ((= n 1) 1)
        ((= n 2) 5)
        ((= n 3) 10)
        ((= n 4) 25)
        ((= n 5) 50)))
