(defparameter elements '(H He Li Be B C N O F Ne Na Mg Al Si P S Cl Ar K Ca Sc Ti V Cr Mn Fe Co Ni Cu Zn Ga Ge As Se Br Kr Rb Sr Y Zr Nb Mo Tc Ru Rh Pd Ag Cd In Sn Sb Te I Xe Cs Ba La Ce Pr Nd Pm Sm Eu Gd Tb Dy Ho Er Tm Yb Lu Hf Ta W Re Os Ir Pt Au Hg Tl Pb Bi Po At Rn Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf Db Sg Bh Hs Mt Ds Rg Cn Nh Fl Mc Lv Ts Og))

(defparameter element-names '((H "Hidrogênio")
                              (He "Hélio")
                              (Li "Lítio")
                              (Be "Berílio")
                              (B "Boro")
                              (C "Carbono")
                              (N "Nitrogênio")
                              (O "Oxigênio")
                              (F "Flúor")
                              (Ne "Neônio")
                              (Na "Sódio")
                              (Mg "Magnésio")
                              (Al "Alumínio")
                              (Si "Silício")
                              (P "Fósforo")
                              (S "Enxofre")
                              (Cl "Cloro")
                              (Ar "Argônio")
                              (K "Potássio")
                              (Ca "Cálcio")
                              (Sc "Escândio")
                              (Ti "Titânio")
                              (V "Vanádio")
                              (Cr "Cromo")
                              (Mn "Manganês")
                              (Fe "Ferro")
                              (Co "Cobalto")
                              (Ni "Níquel")
                              (Cu "Cobre")
                              (Zn "Zinco")
                              (Ga "Gálio")
                              (Ge "Germânio")
                              (As "Arsênio")
                              (Se "Selênio")
                              (Br "Bromo")
                              (Kr "Criptônio")
                              (Rb "Rubídio")
                              (Sr "Estrôncio")
                              (Y "Ítrio")
                              (Zr "Zircônio")
                              (Nb "Nióbio")
                              (Mo "Molibdênio")
                              (Tc "Tecnécio")
                              (Ru "Rutênio")
                              (Rh "Ródio")
                              (Pd "Paládio")
                              (Ag "Prata")
                              (Cd "Cádmio")
                              (In "Índio")
                              (Sn "Estanho")
                              (Sb "Antimônio")
                              (Te "Telúrio")
                              (I "Iodo")
                              (Xe "Xenônio")
                              (Cs "Césio")
                              (Ba "Bário")
                              (La "Lantânio")
                              (Ce "Cério")
                              (Pr "Praseodímio")
                              (Nd "Neodímio")
                              (Pm "Promécio")
                              (Sm "Samário")
                              (Eu "Európio")
                              (Gd "Gadolínio")
                              (Tb "Térbio")
                              (Dy "Disprósio")
                              (Ho "Hólmio")
                              (Er "Érbio")
                              (Tm "Túlio")
                              (Yb "Itérbio")
                              (Lu "Lutécio")
                              (Hf "Háfnio")
                              (Ta "Tântalo")
                              (W "Tungstênio")
                              (Re "Rênio")
                              (Os "Ósmio")
                              (Ir "Irídio")
                              (Pt "Platina")
                              (Au "Ouro")
                              (Hg "Mercúrio")
                              (Tl "Tálio")
                              (Pb "Chumbo")
                              (Bi "Bismuto")
                              (Po "Polônio")
                              (At "Astato")
                              (Rn "Radônio")
                              (Fr "Frâncio")
                              (Ra "Rádio")
                              (Ac "Actínio")
                              (Th "Tório")
                              (Pa "Protactínio")
                              (U "Urânio")
                              (Np "Neptúnio")
                              (Pu "Plutônio")
                              (Am "Amerício")
                              (Cm "Cúrio")
                              (Bk "Berquélio")
                              (Cf "Califórnio")
                              (Es "Einstênio")
                              (Fm "Férmio")
                              (Md "Mendelévio")
                              (No "Nobelio")
                              (Lr "Laurêncio")
                              (Rf "Rutherfórdio")
                              (Db "Dúbnio")
                              (Sg "Seabórgio")
                              (Bh "Bóhrio")
                              (Hs "Hássio")
                              (Mt "Meitnério")
                              (Ds "Darmstádtio")
                              (Rg "Roentgênio")
                              (Cn "Copernício")
                              (Nh "Nihônio")
                              (Fl "Fleróvio")
                              (Mc "Moscóvio")
                              (Lv "Livermório")
                              (Ts "Tenessino")
                              (Og "Oganessônio")))
                              
(defun element-name (elt)
  (cadr (assoc elt element-names)))

(defun say-with-elements (letters)
  (unless (null letters)
    (let* ((a (car letters))
           (b (cadr letters))
           (rest (cddr letters)))
      (multiple-value-bind (element both) (say a b)
        (when element
          (format t "~A " element))
        (if both
            (cons element (say-with-elements rest))
            (cons element (say-with-elements (cdr letters))))))))

(defun say (a b)
  (if b
      (let ((new-symbol (concatenate-symbols a b)))
        (if (member (concatenate-symbols a b) elements)
            (values new-symbol t)
            (say a nil)))
      (if (member a elements)
          a
          (let ((found-elt
                  (find (symbol-name a) elements :key #'(lambda (elt) (subseq (symbol-name elt) 0 1)) :test #'equal)))
            (values (or found-elt nil) nil)))))

(defun concatenate-symbols (a b)
  (intern (concatenate 'string (symbol-name a) (symbol-name b))))
  
